// Generated by CoffeeScript 1.10.0
(function() {
  var App;

  App = {};


  /*
  	Init
   */

  App.init = function() {
    App.canvas = document.createElement('canvas');
    App.canvas.height = 400;
    App.canvas.width = 800;
    document.getElementsByTagName('article')[0].appendChild(App.canvas);
    App.ctx = App.canvas.getContext("2d");
    App.ctx.fillStyle = "solid";
    App.ctx.strokeStyle = "#ECD018";
    App.ctx.lineWidth = 5;
    App.ctx.lineCap = "round";
    App.ctx.fillRect(10, 10, 200, 200);
    App.socket = io.connect('http://localhost:9191');
    App.socket.on('draw', function(data) {
      return console.log(data);
    });
    App.draw = function(type, x, y, w, h) {
      if (type === "rect") {
        return App.ctx.fillRect(x, y, w, h);
      } else {
        return console.log(type + "not implemented");
      }
    };
  };


  /*
  	Draw Events
   */

  $(function() {
    return App.init();
  });

}).call(this);

//# sourceMappingURL=scripts.js.map
